### ISSUE TITLE
Extend Fiori Pipeline with SAP SolMan Steps

### ISSUE THREAD

**Issue by 1084565** [SAP/jenkins-pipelines#11]
The CM scenario is an extension to the existing fiori, i.e. building and deploying remains the same and we have additional/optional SolMan Steps.

## Details
* we need to adjust the configuration (backwards compatibility issues)
* we will introduce skip config parameters for cm related steps, follow apollo convention
* customers can still configure to skip all cm related steps and execute the pure CI+Neo scenario (default)

## Done If
Pipeline template can be used by customers to run the teched solman/CM scenario.

**Comment by ebratz** [comment]
Hi!
Any update on this topic? We are waiting to implement the fully automated CTS+ for XSA on premise using Solman with ChaRM.
Thanks in advance

**Comment by marcusholl** [comment]
Hi,

thanks a lot for your request.

Steps for implementing a SAP-SolutionManager based scenario are already in place:
* checkChangeInDevelopment ([impl](https://github.com/SAP/jenkins-library/blob/master/vars/checkChangeInDevelopment.groovy), [docu](https://sap.github.io/jenkins-library/steps/checkChangeInDevelopment/))
* transportRequestCreate ([impl](https://github.com/SAP/jenkins-library/blob/master/vars/transportRequestCreate.groovy), [docu](https://sap.github.io/jenkins-library/steps/transportRequestCreate/))
* transportRequestUploadFile ([impl](https://github.com/SAP/jenkins-library/blob/master/vars/transportRequestUploadFile.groovy), [docu](https://sap.github.io/jenkins-library/steps/transportRequestUploadFile/))
* transportRequestRelease  ([impl](https://github.com/SAP/jenkins-library/blob/master/vars/transportRequestRelease.groovy), [docu](https://sap.github.io/jenkins-library/steps/transportRequestRelease/))

An minimalistic example pipeline looks like:

```
@Library('piper-library-os') _

node() {

  stage('prepare') {

      checkout scm

      setupCommonPipelineEnvironment script:this

      checkChangeInDevelopment script: this
  }

  stage('build') {
      mtaBuild script: this
  }

  stage('solmanUpload') {
      transportRequestUploadFile script:this
  }
}
```

The changeDocumentId and the transportRequestId needs to be provided inside the git commit messages, see step docu for more details. In this pipeline we expect the transport request to be created beforehand. It is also possible to create the transport request with a pipeline step.

At the moment there is only the step docu. We are working on a corresponding documentation of the full scenario.

Please come back again in case of further questions.

Marcus

**Comment by ebratz** [comment]
Hi Marcus,
Thanks for the reply. So, sounds like this issue is closed already? Do you have the links for the updated documentation on how to implement the entire solution?
Thanks in advance

**Comment by 1084565** [comment]
Hi @ebratz , here's the link to the documentation:
https://sap.github.io/jenkins-library/scenarios/changeManagement/
