### ISSUE TITLE
Add support to deploy to on premise Gateway landscape

### ISSUE THREAD

**Issue by tchampag** [SAP/jenkins-pipelines#14]
Had a call with you yesterday and discussed this project.  It was mentioned that support gateway deployment is in process and projected to be supported in early 2019.  I wanted to create an issue around this to show we want this functionality and to be able to track progress towards that goal.

**Comment by marcusholl** [comment]
@1084565 : Can you provide more details on that, please?

**Comment by radsoulbeard** [comment]
@tchampag: Please find the requirements for AS ABAP and SAPUI here https://github.com/SAP/devops-cm-client ad the Readme.md

**Comment by 1084565** [comment]
@tchampag Did that work for you?

**Comment by marcusholl** [comment]
Since there is no traffic on this issue I close it.
