### ISSUE TITLE
Move MTA_HOME and NEO_HOME out of .pipeline/config.properties

### ISSUE THREAD

**Issue by marcusholl** [SAP/jenkins-pipelines#4]
```.pipeline/config.properties``` should hold project specific configuration items, like deploy accounts.
It should not contain build server specific items, like home directories of tools.

The point is: project responsible persons can maintain project specific settings. but they cannot in a reasonable way maintain settings which relates to the build server in the narrower sense. In case the project is built on different build servers with a different setup the build will fail.

Suitable approaches for improving the status:

* put the tools in the path so that they can be found out of the box.
* provide the tools inside a docker image and run the corresponding actions inside a docker container. 
* provide the tools in the resources folder of the piper-library and reference the tools accordingly (requires jenkins specific knowledge about the sync point of the piper lib, does not work for tools with a special delivery channel).

**Comment by lopezmau** [comment]
From my point of view, option 2 (Docker image) would make more sense. It will provide a way to share build tools among different projects, so project responsible don't worry about settings on those tools.
Moreover, this solution is more in line with the modern CI/CD strategy, where Docker and component integration is key.

**Comment by 1084565** [comment]
I agree with @lopezmau on the docker image. It might take some time to get there though, at least for some of the tools. We will need to check the legal implications.

**Comment by kbarnold** [comment]
Yes, indeed. Docker is definitely the best solution, but that will take some time.
What is the preferred solution in the meantime? Is it acceptable for users to configure build server specific properties like MTA_HOME and NEO_HOME on the build server only? Or do we need to support configuring those properties in each project? The latter would also require a certain amount of communication between build server maintainers and development while sacrificing clearness of the contract where what should be configured.

**Comment by lopezmau** [comment]
I would say, it will be better to configure those properties on the build server only. It will help in case there are any changes on the path or the way those tools are installed, it will be transparent for development team.

**Comment by radsoulbeard** [comment]
Docker images are available now, look at here: https://github.com/SAP/devops-docker-images
